# homelab/services/docker-compose/media/prowlarr/docker-compose.yml
networks:
  srv-net:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      srv-net:
        ipv4_address: ${CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}:/config
