---
services:
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --storage.path=/alertmanager
    volumes:
      - ${APPDATA}/config/config.yml:/etc/alertmanager/config.yml:ro
      - ${APPDATA}/data:/alertmanager
    networks:
      srv-net:
        ipv4_address: ${CONTAINER_IP}

networks:
  srv-net:
    external: true
    name: srv-net
