---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${APPDATA}:/app/data
    networks:
      srv-net:
        ipv4_address: ${CONTAINER_IP}

networks:
  srv-net:
    external: true
    name: srv-net
