---
services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    volumes:
      - ${APPDATA}:/app/config
    networks:
      srv-net:
        ipv4_address: ${CONTAINER_IP}

networks:
  srv-net:
    external: true
    name: srv-net
