all:
  children:
    proxmox:
      hosts:
        pve-router:
          ansible_host: 192.168.1.135
        pve-main:
          ansible_host: 10.0.5.12
        pve-aux:
          ansible_host: 10.0.5.13
    docker_hosts:
      hosts:
        docker-main:
          ansible_host: 10.0.30.20
        docker-aux:
          ansible_host: 10.0.30.21
        docker-nas:
          ansible_host: 10.0.5.10
    nas:
      hosts:
        nas-01:
          ansible_host: 10.0.5.10