networks:
  srv-net:
    external: true

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    networks:
      srv-net:
        ipv4_address: ${CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}:/config
      - ${MEDIA}/tv:/tv
      - ${MEDIA}/movies:/movies
